version: '3'

services: # adds 2 services: mysql and phpmyadmin to connect with
  db:
    image: mysql # use latest version of mysql
    container_name: db # add a name for the container
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment: # add default values, see docs for more info.
      MYSQL_USER: user 
      MYSQL_ROOT_PASSWORD: mypassword
      MYSQL_PASSWORD: mypassword 
      MYSQL_DATABASE: blog # create this database on startup
      MYSQL_ROOT_HOST: '%'
    ports:
      - '3306:3306'
    networks:
      - backend
    volumes:
      - my-datavolume:/var/lib/mysql 
  
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin
    ports:
     - "8081:80"
    environment:
      MYSQL_ROOT_PASSWORD: mypassword #(Required) set the password for the root superuser account.
      PMA_HOST: db   # define the address/hostname of the mysql server eg mysql container name.
      PMA_USER: root # this is the root user to login on startup
      PMA_PASSWORD: mypassword # use the root password to login on startup.
    depends_on:
      - db
    networks:
      - backend
      
  app:
    #build: 
     # context: ./
    #  dockerfile : ./Dockerfile
    image: mohamedfadhel404/blogsymfony:1.2
    ports:
      - 800:80
    entrypoint: [ "bash", "-c", "sleep 10 && php bin/console make:migration && php bin/console doctrine:migrations:migrate --no-interaction --allow-no-migration && exec apache2-foreground "] 
    depends_on:
      - db
    networks:
      - backend
    environment:
      DATABASE_URL: mysql://root:mypassword@db:3306/blog?serverVersion=5.7
    labels:
      kompose.service.type: LoadBalancer

  
networks:
  backend : 
volumes:
  my-datavolume : 
 # 