apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -o k8s/
    kompose.service.type: LoadBalancer
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: app
  name: app
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: app
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -o k8s/
        kompose.service.type: LoadBalancer
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.network/backend: "true"
        io.kompose.service: app
    spec:
      containers:
        - command:
            - bash
            - -c
            - 'sleep 10 && php bin/console make:migration && php bin/console doctrine:migrations:migrate --no-interaction --allow-no-migration && exec apache2-foreground '
          env:
            - name: DATABASE_URL
              value: mysql://root:mypassword@db:3306/blog?serverVersion=5.7
          image: mohamedfadhel404/blogsymfony:1.2
          name: app
          ports:
            - containerPort: 80
          resources: {}
      restartPolicy: Always
status: {}
