apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -o k8s/
    kompose.service.type: LoadBalancer
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: app-tcp
  name: app-tcp
spec:
  ports:
    - name: "800"
      port: 800
      targetPort: 80
  selector:
    io.kompose.service: app
  type: LoadBalancer
status:
  loadBalancer: {}
