<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerX7DjXF1\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerX7DjXF1/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerX7DjXF1.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerX7DjXF1\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerX7DjXF1\App_KernelDevDebugContainer([
    'container.build_hash' => 'X7DjXF1',
    'container.build_id' => '111345b5',
    'container.build_time' => 1656863775,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerX7DjXF1');
